---

# expected inventory:
#
#                           [group]
#                      web worker db queue dynamic
#         WEB          X                   X
# [host]  WORK             X               X
#         DB+Q                    X  X
#         QUEUE                      X

- include: wait_for_ssh.yml
- include: gather_facts.yml

- hosts: dynamic
  user: ubuntu
  become: true
  tasks:
    - name: nginx | ssl dir | create
      file:
        path: /etc/nginx/ssl
        owner: root
        group: root
        state: directory
        mode: "0770"

    - name: nginx | ssl key | create
      template:
        src: ../templates/ssl_key.j2
        dest: /etc/nginx/ssl/www_osumo_org.key

    - name: nginx | ssl cert | create
      template:
        src: ../templates/ssl_cert.j2
        dest: /etc/nginx/ssl/www_osumo_org.pem

    - name: nginx | ssl dhparams | create
      template:
        src: ../templates/ssl_dhparams.j2
        dest: /etc/nginx/ssl/dhparams.pem

    - name: nginx | configure
      template:
        src: ../templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/sumo

    - name: disable default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: enable girder nginx site
      file:
        path: /etc/nginx/sites-enabled/sumo
        src: /etc/nginx/sites-available/sumo
        state: link

- hosts: dynamic
  user: ubuntu
  become: true
  become_user: girder
  tasks:
    - name: resonant | configure
      template:
        src: "../templates/{{ item.src }}.j2"
        dest: "/opt/osumo-project/{{ item.dest }}"
      with_items:
        - src: girder.local.cfg
          dest: girder/girder/conf/girder.local.cfg
        - src: worker.local.cfg
          dest: girder_worker/girder_worker/worker.local.cfg
        - src: girder.bash
          dest: girder.bash
        - src: worker.bash
          dest: worker.bash

- hosts: worker
  user: ubuntu
  become: true
  tasks:
    - name: girder worker | service | stop
      service:
        name: girder_worker
        state: stopped

    - name: wait for 10 seconds
      local_action: wait_for timeout=10

    - name: girder worker | service | start
      service:
        name: girder_worker
        state: started

- hosts: queue
  user: ubuntu
  become: true
  tasks:
    - name: restart rabbitmq
      service:
        name: rabbitmq-server
        state: restarted

- hosts: web
  user: ubuntu
  become: true
  tasks:
    - name: girder | service | start
      service:
        name: girder
        state: restarted

    - name: girder | nginx | start
      service:
        name: nginx
        state: restarted

- include: wait_for_girder.yml

