
- hosts: web
  user: ubuntu
  become: true
  connection: local
  gather_facts: no
  tasks:
    - name: wait for girder
      local_action: "\
        wait_for \
          host={{ inventory_hostname }} \
          port=8080 \
          timeout=900 \
          state=started"

